openapi: 3.0.1
info:
  description: This is the swagger file for easy cryptowallet BIP44 service.
  version: "1.0.0"
  title: BIP44 Api
paths:
  /ping:
    get:
      summary: Ping
      tags:
        - Test
      operationId: "operations.ping.pong"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
          description: Successful test
        '520':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
          description: Internal server error
  /generate_mnemonic_phrase:
    get:
      summary: Generating mnemonic phrase
      tags:
        - Mnemonic phrase
      operationId: "operations.mnemonic_phrase.generate_mnemonic_phrase"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateMnemonicPhraseResponse'
          description: Mnemonic phrase received.
        '520':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
          description: Internal server error
  /get_blockNumber:
    get:
      summary: Get block number in Ethereum mainnet
      tags:
        - Blockchain info
      operationId: "operations.blockchain_info.get_blockNumber"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBlockNumberResponse'
          description: Block number of Ethereum mainnet received.
        '520':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
          description: Internal server error
  /get_eth_balance/{account_address}:
    get:
      summary: Takes balance from Ethereum address
      tags:
        - AccountInfo
      operationId: "operations.account_info.get_eth_balance"
      parameters:
        - name: account_address
          in: path
          description: Address of Ethereum account
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEthBalanceResponse'
          description: Balance of Ethereum account received.
        '520':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
          description: Internal server error
components:
  schemas:
    PingResponse:
      type: object
      properties:
        message:
          type: string
          example: pong
    GenerateMnemonicPhraseResponse:
      type: object
      properties:
        mnemonic_phrase:
          type: array
          items:
            type: string
    GetEthBalanceResponse:
      type: object
      properties:
        balance:
          type: number
    GetBlockNumberResponse:
      type: object
      properties:
        balance:
          type: integer
    InternalError:
      type: object
      properties:
        error_type:
          type: string
          example: error
        error_message:
          type: string
          example: 'No access to the service.'
  parameters:
    passphrase:
      name: passphrase
      in: query
      required: true
      description: Password phrase
      schema:
        type: string